# -*- coding: utf-8 -*-
"""Scrapping_assignment(page2)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vDAp2l0fyqrxMfKwdIMAMSE0TRP4nt-j
"""

import requests
import pandas as pd
from bs4 import BeautifulSoup
import urllib
from bs4 import BeautifulSoup as BS

URL_flip="https://www.instructables.com/Hydraulic-Craft-Stick-Box/"
r_flip = requests.get(URL_flip) 

c_flip=r_flip.content
soup_f=BeautifulSoup(c_flip,"html.parser")
soup_k=BeautifulSoup(c_flip,"lxml")
#print(soup_f)

header=soup_f.find("h1",{"class":"header-title"}).text##Gettting the header_title
view=soup_f.find("p",{"class":"svg-views view-count"}).text##Getting view count
fav=soup_f.find("p",{"class":"svg-favorite active favorite-count"}).text##getting fav count
comment=soup_f.find("p",{"class":"svg-comments active comment-count"}).text##Getting comment count

##############Getting steps############

##Step 1 

steps1=soup_f.find_all("section",{"id":"step1"})## Getting the steps 

##Step 2

steps2=soup_f.find_all("section",{"id":"step2"})## Getting the steps 

##Step 3 

steps3=soup_f.find_all("section",{"id":"step3"})## Getting the steps 

###Step 4 

steps4=soup_f.find_all("section",{"id":"step4"})## Getting the steps 

###Step 5

steps5=soup_f.find_all("section",{"id":"step5"})## Getting the steps 

###Step 6

steps6=soup_f.find_all("section",{"id":"step6"})## Getting the steps 

###Step 7

steps7=soup_f.find_all("section",{"id":"step7"})## Getting the steps 

###Supplies 

suppli=soup_f.find("div",{"class":"step-body"})



###Gettting Youtube URL
###Getting all the links and then getting the youtube link

linklist=[]
link=soup_k.find_all('div',class_='videoset-item')

   

###Getting imgs 
suppli=soup_f.find("div",{"class":"step-body"})

final_list=[]
## Final List order [url,header,view_count, favourite_count, comment_count,Youtube_url,steps,supplies]

final_list.append(URL_flip)
print("URL =",URL_flip)
print("Header =",header)
final_list.append(header)
print("View Count=",view)
final_list.append(view)
print(f"fav _count=",fav)
final_list.append(fav)
print("Comment count =",comment)
final_list.append(comment)
print("Youtube link=",youtube_url)
final_list.append(youtube_url)


##Extracting Steps
d=[] 

for item in steps1:
   
   d.append("Step 1")
   d.append(item.find("div",{"class","step-body"}).text)

for item in steps2:
    d.append("Step 2")
    d.append(item.find("div",{"class","step-body"}).text)

for item in steps3:
    d.append("Step 3")
    d.append(item.find("div",{"class","step-body"}).text)   

for item in steps4:
    d.append("Step 4")
    d.append(item.find("div",{"class","step-body"}).text)

for item in steps5:
    d.append("Step 5")
    d.append(item.find("div",{"class","step-body"}).text)

for item in steps6:
    d.append("Step 6")
    d.append(item.find("div",{"class","step-body"}).text)

for item in steps7:
    d.append("Step 7")
    d.append(item.find("div",{"class","step-body"}).text)

print("Steps =",d)

final_list.append(d)

###Supplies 
spu=suppli.find_all("li")
i=0
spu1=[]
for item in spu:
  if i==8:
    break
  spu1.append(spu[i].text)
  i=i+1
  


print("Supplies =",spu1)

final_list.append(spu1)


###

###Converting list to json 
import json 

final_json=json.dumps(final_list)