# -*- coding: utf-8 -*-
"""Scrapping_assignment(page3).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JhjwSF2xrJvsevvAVpo9kh_RRtDArDQl
"""

import requests
import pandas as pd
from bs4 import BeautifulSoup
import urllib
from bs4 import BeautifulSoup as BS

URL_flip="https://www.instructables.com/How-to-Make-a-Self-Watering-Plant-Stand/"
r_flip = requests.get(URL_flip) 

c_flip=r_flip.content
soup_f=BeautifulSoup(c_flip,"html.parser")

#print(soup_f)

header=soup_f.find("h1",{"class":"header-title"}).text##Gettting the header_title
view=soup_f.find("p",{"class":"svg-views view-count"}).text##Getting view count
fav=soup_f.find("p",{"class":"svg-favorite active favorite-count"}).text##getting fav count


print(header)
print(view)
print(fav)

##############Getting steps############

##Step 1 

steps1=soup_f.find_all("section",{"id":"step1"})## Getting the steps 

##Step 2

steps2=soup_f.find_all("section",{"id":"step2"})## Getting the steps 

##Step 3 

steps3=soup_f.find_all("section",{"id":"step3"})## Getting the steps 

###Step 4 

steps4=soup_f.find_all("section",{"id":"step4"})## Getting the steps 

###Step 5

steps5=soup_f.find_all("section",{"id":"step5"})## Getting the steps 

###Step 6

steps6=soup_f.find_all("section",{"id":"step6"})## Getting the steps 

###Step 7

steps7=soup_f.find_all("section",{"id":"step7"})## Getting the steps 

###Step 8 

steps8=soup_f.find_all("section",{"id":"step8"})## Getting the steps 

###Step 9

steps9=soup_f.find_all("section",{"id":"step9"})## Getting the steps 

###Gettting Youtube URL
###Getting all the links and then getting the youtube link
linklist=[]
for link in soup_f.find_all('a'):
    linklist.append(link.get('href'))

youtube_url=linklist[21]


####Supplies 
suppli=soup_f.find("div",{"class":"step-body"})

final_list=[]
## Final List order [url,header,view_count, favourite_count,Youtube_url,steps,supplies]

final_list.append(URL_flip)
print("URL =",URL_flip)
print("Header =",header)
final_list.append(header)
print("View Count=",view)
final_list.append(view)
print(f"fav _count=",fav)
final_list.append(fav)
print("Comment count =",comment)
final_list.append(comment)
print("Youtube link=",youtube_url)
final_list.append(youtube_url)


##Extracting Steps
d=[] 

for item in steps1:
   
   d.append("Step 1")
   d.append(item.find("div",{"class","step-body"}).text)

for item in steps2:
    d.append("Step 2")
    d.append(item.find("div",{"class","step-body"}).text)

for item in steps3:
    d.append("Step 3")
    d.append(item.find("div",{"class","step-body"}).text)   

for item in steps4:
    d.append("Step 4")
    d.append(item.find("div",{"class","step-body"}).text)

for item in steps5:
    d.append("Step 5")
    d.append(item.find("div",{"class","step-body"}).text)

for item in steps6:
    d.append("Step 6")
    d.append(item.find("div",{"class","step-body"}).text)

for item in steps7:
    d.append("Step 7")
    d.append(item.find("div",{"class","step-body"}).text)


for item in steps8:
    d.append("Step 8")
    d.append(item.find("div",{"class","step-body"}).text)

for item in steps9:
    d.append("Step 9")
    d.append(item.find("div",{"class","step-body"}).text)


print("Steps =",d)

final_list.append(d)
 
###Extracting supplies 
spu=suppli.find_all("p")

sup=[]
i=0
for item in spu:
  
  sup.append(item)
sup.pop(0)
print("Supplies =",sup)
final_list.append(sup)


###

###Converting list to json 
import json 

final_json=json.dumps(final_list)